---
sudo: required
dist: trusty
language: node_js
node_js:
  - 6
  - 8
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
#install:
#  - npm install
#before_script:
#  - export CI=false
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build
  on:
    branch: master
